name: AntryDeathEffects
version: '${project.version}'
main: dev.antry.antrydeatheffects.AntryDeathEffects
api-version: '1.20'
commands:
  deatheffects:
    description: Open the death effects GUI
    usage: /<command>
    aliases: [de, effects]
permissions:
  antrydeatheffects.use:
    description: Allows using the death effects command
    default: true
  antrydeatheffects.effect.lightning:
    description: Allows using the lightning effect
    default: true
  antrydeatheffects.effect.explosion:
    description: Allows using the explosion effect
    default: true
  antrydeatheffects.effect.flyinganimals:
    description: Allows using the flying animals effect
    default: true
