# AntryDeathEffects Configuration

# Default effects settings
effects:
  flying-animals:
    duration: 40 # Duration in ticks (2 seconds)
    firework:
      power: 2
      enabled-by-default: true
    velocity:
      vertical: 0.6
      horizontal: 0.6
      upward-offset: 0.2

  soul-escape:
    duration: 40 # Duration in ticks (2 seconds)
    bat-count: 12
    velocity:
      base: 1.2
      random-factor: 0.5
    smoke-particles: true

  grave:
    duration: 100 # Duration in ticks (5 seconds)
    years:
      min: 2000
      max: 2024
    colors:
      title: "§c§l"    # Red and bold
      name: "§e"       # Yellow
      subtitle: "§7"   # Gray
      date: "§8"       # Dark gray

  lightning:
    strike-count: 1
    fire: false

  explosion:
    power: 0
    fire: false
    break-blocks: false

# Messages
messages:
  no-permission: "&cYou don't have permission to use this!"
  gui-title: "&5Death Effects" 